name: vrijedenkers
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010004'
    - '#edffff'
    - '#51a2ff'
    - '#80531f'
    - '#d9bfb0'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
